[project]
name = "pmc-citation-network"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lxml>=6.0.0",
    "sqlmodel>=0.0.24",
    "tqdm>=4.67.1",
    "typer>=0.16.0",
]
